### ISSUE TITLE
EDDF 25L

### ISSUE THREAD

**Issue by MajorTomMueller** [ECoops-123/IF-Navigation#3]
[[EDDF 25L ILS Incorrect - Support - Infinite Flight Community](https://community.infiniteflight.com/t/ils-approach-eddf/734976), [Eddf ils 25r - Support - Infinite Flight Community](https://community.infiniteflight.com/t/eddf-ils-25r/736500)](url)

**Comment by MajorTomMueller** [comment]
needs to be checked in the code

**Comment by carmichaelalonso** [comment]
For in-app issues, let's just report them through beta. We won't be able to keep track of this issue tracker as well and I fear it would get lost.

Thanks for transferring things over though :)
