### ISSUE TITLE
WAHI 29 ILS missing

### ISSUE THREAD

**Issue by Starlian1** [ECoops-123/IF-Navigation#39]
Airport ICAO:

WAHI

Runways being modified:

29

Are you working on this?
Yes

Additional Information:

**Comment by VibrantPixel** [comment]
[https://github.com/ECoops-123/IF-Navigation/commit/a646e75de54a16a48fd00dc7d4ec9f56329bcf18](url)

**Comment by MajorTomMueller** [comment]
This issue still, or again, exists

**Comment by alexgankov** [comment]
RWY 29 does not seem to have ILS available (see screenshot of available approaches from Navigraph below). However, I found that RWY 11's ILS is missing. Working on adding it at the moment.

![image](https://github.com/user-attachments/assets/59a0707f-855c-408f-afd9-6fe7a1c230d9)
